// <auto-generated />
using System;
using MamaWash.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MamaWash.Migrations
{
    [DbContext(typeof(MamaWashContext))]
    [Migration("20190620074053_ConvertedAccountNumberToINt")]
    partial class ConvertedAccountNumberToINt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MamaWash.Models.BankList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bank");

                    b.Property<string>("BankCode");

                    b.HasKey("ID");

                    b.ToTable("BankList");
                });

            modelBuilder.Entity("MamaWash.Models.Beneficiaries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName");

                    b.Property<int>("AccountNumber")
                        .HasMaxLength(10);

                    b.Property<int?>("BankCodeID");

                    b.Property<string>("BankID");

                    b.Property<int?>("BankNameID");

                    b.Property<string>("RecipientCode");

                    b.HasKey("ID");

                    b.HasIndex("BankCodeID");

                    b.HasIndex("BankNameID");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("MamaWash.Models.TransactionHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BeneficiariesID");

                    b.HasKey("ID");

                    b.HasIndex("BeneficiariesID");

                    b.ToTable("TransactionHistory");
                });

            modelBuilder.Entity("MamaWash.Models.Beneficiaries", b =>
                {
                    b.HasOne("MamaWash.Models.BankList", "BankCode")
                        .WithMany()
                        .HasForeignKey("BankCodeID");

                    b.HasOne("MamaWash.Models.BankList", "BankName")
                        .WithMany()
                        .HasForeignKey("BankNameID");
                });

            modelBuilder.Entity("MamaWash.Models.TransactionHistory", b =>
                {
                    b.HasOne("MamaWash.Models.Beneficiaries")
                        .WithMany("Transactions")
                        .HasForeignKey("BeneficiariesID");
                });
#pragma warning restore 612, 618
        }
    }
}
